In [9]:
import numpy as np

In [10]:
# 一、numpy数组——ndarray：一种多维数组对象：

# - 数组中的所有元素必须是相同类型的；
# - shape：数组的维度
# - dtype：数组中元素的数据类型

In [17]:
data = np.array([[0.9, 0.8], [0.7, 0.6], [0.5, 0.4]])

In [18]:
data

array([[0.9, 0.8],
       [0.7, 0.6],
       [0.5, 0.4]])

In [19]:
data.shape

(3, 2)

In [20]:
data.dtype

dtype('float64')

In [21]:
# 二、如何创建numpy数组ndarray：

In [22]:
# 2.1 使用array()函数，接受一个序列型的对象，输出一个numpy数组

In [23]:
data1 = [1,2,3]

In [28]:
arr1 = np.array(data1)
arr1

array([1, 2, 3])

In [29]:
arr1.shape

(3,)

In [26]:
# 多维数组
data2 = [[1,2,3],[4,5,6]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr2.shape

(2, 3)

In [31]:
# 2.2 zeros()、ones()、empty()：

In [35]:
#（1）zeros()：创建元素全为0的数组
# 一维全0数组
arr3 = np.zeros(3)
arr3

array([0., 0., 0.])

In [36]:
# 多维全0数组：
arr4 = np.zeros((2,3))
arr4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
#（2）ones()创建元素全为1的数组：
# 一维
arr5 = np.ones(3)
arr5

array([1., 1., 1.])

In [51]:
# 多维数组
arr6 = np.ones((3,4))
arr6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
# （3） empty()创建一个在占用内存为0的数组

In [ ]:
# 注意：empty()返回的是未初始化的垃圾值，而一般不都是0

In [44]:
arr7 = np.empty((2,3))
arr7

array([[0.9, 0.8, 0.7],
       [0.6, 0.5, 0.4]])

In [45]:
# 2.3 arange：
# arange是range函数的numpy数组版

In [46]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
# 三、ndarray数据类型：

In [52]:
# 3.1 可以通过astype()转换dtype类型

In [55]:
arr8 = np.array([1,2,3,4,5])
arr8.dtype

dtype('int32')

In [58]:
float_arr8 = arr8.astype(np.float64)
float_arr8.dtype

dtype('float64')

In [59]:
# （1）如果将浮点数，转换成整数，则小数部分会被抹去

In [60]:
arr9 = np.array([3.7, -1.2, -2.6, 0.5])
arr9

array([ 3.7, -1.2, -2.6,  0.5])

In [62]:
arr9 = arr9.astype(np.int32)
arr9

array([ 3, -1, -2,  0])

In [63]:
# （2）如果某字符串数组全是数字，也可以用astype将其转换成数值形式

In [67]:
arr10 = np.array(['1.25', '-9.6', '42'])
print(arr10)
arr10.dtype

['1.25' '-9.6' '42']


dtype('<U4')

In [70]:
arr10 = arr10.astype(float)
print(arr10)
arr10.dtype

[ 1.25 -9.6  42.  ]


dtype('float64')

In [71]:
# （3）使用简洁类型代码来表示dtype

In [73]:
arr11 = np.ones(5, dtype='u4')  #  np.ones(5, dtype=np.int32)
arr11

array([1, 1, 1, 1, 1], dtype=uint32)

In [74]:
# 注意：调用astype无论如何都会创建出一个新的数组（原始数据的一份拷贝），及时新的dtype跟老的dtype相同也是如此

In [75]:
# 四、基本的索引和切片：

In [79]:
# 数组的切片是原始数组的视图，这意味着数据不会被复制，视图上的任何修改都会直接反映在源数组上
# 如果你想要的得到的是数组ndarray的一份副本，而非视图的话，就需要显式的进行复制.copy()，例如：arr[5:8].copy()

In [80]:
# 4.1 一维数组：

In [95]:
arr12 = np.arange(10)
arr12

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
arr12[5]

5

In [97]:
arr12[5:8]

array([5, 6, 7])

In [98]:
arr12[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
arr12[5:8] = 12
arr12

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [ ]:
# 这些返回的都是数组的视图

In [100]:
# （2）二维数组或高维数组：

In [103]:
arr13 = np.array([[1,2,3],[4,5,6]])
arr13

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
arr13[0][2]

3

In [105]:
arr13[0,2]

3

In [109]:
# 这两个方式是等价的

In [108]:
# 五、切片索引：

In [110]:
# 可以在一个或者多个轴上进行切片，也可以跟整数索引混合使用

In [111]:
arr14 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr14

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
arr14[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
arr14[1: ,0:2]

array([[4, 5],
       [7, 8]])

In [115]:
# 六、布尔型索引：

In [117]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [122]:
data = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,13],[13,14,15],[16,17,18],[19,20,21]])
data

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 13],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [124]:
# 生成布尔型数组
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [125]:
# names数组中的每个元素，对应data数组中的一行
# 要选出data数组中对应于names数组中的'Bob'的所有行
data[names == 'Bob']

array([[ 1,  2,  3],
       [10, 11, 13]])

In [126]:
# 注意：1.布尔型数组(names=='Bob')的长度，必须跟被索引的轴长度一样
# 2.python关键字and、or在布尔型数组中无效
# 3.且：&；或：|；非：-
# 4.通过布尔型索引选取数组中的数据，将总是创建数据的副本，及时返回一模一样的数据，也如此。

In [127]:
data

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 13],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [128]:
# 七、花式索引：
# 为了以特定顺序选取行子集，需要传入一个用于指定顺序的整数索引列表或者ndarray
# 使用负数索引将会从末尾开始选取行

In [129]:
# 7.1 以特定顺序选取行子集
arr15 = np.empty((8,4))
for i in range(8):
    arr15[i]=i
arr15

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [132]:
arr15[[4,3,0,-1,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [7., 7., 7., 7.],
       [6., 6., 6., 6.]])

In [136]:
# 7.2 以特定顺序选取特定位置元素
arr16=np.arange(32).reshape((8,4))
arr16

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [138]:
arr16[[1,5,7,2],[0,3,1,2]]
# 选出的元素为(1,0) (5,3) (7,1) (2,2)

array([ 4, 23, 29, 10])

In [140]:
# 7.3 以特定顺序选取行子集和列子集
arr16[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [142]:
# 7.4 np.ix_()函数：
# np.ix_()函数可以将两个一维整数数组转换为一个用于选取方形区域的索引
arr16[np.ix_([1,5,7,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [143]:
# 7.5 花式索引跟切片不一样，它总是将数据复制到新数组中

In [ ]:
# 八、where——将三元表达式，转换成矢量化版本：
# 矢量化：用数组表达式，替换循环；不用编写循环，即可对数据执行批量运算。
# x if condition else y ———  numpy.where(condition,x,y)

In [145]:
x = np.array([1.1,1.2,1.3,1.4,1.5])
y = np.array([2.1,2.2,2.3,2.4,2.5])
condition = np.array([True,False,True,True,False])
result = np.where(condition,x,y)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [ ]:
# x，y可以不是数组，可以是标量

In [148]:
arr17 = np.random.randn(4,4)
arr17

array([[ 0.17630115,  1.71561881,  0.28636817, -0.24735368],
       [-0.64444354,  0.04468165,  0.99755667,  0.0783664 ],
       [-1.18604229, -0.44967714, -0.00646522, -0.10967671],
       [-1.29897482,  0.30297421,  0.27482557,  0.00728608]])

In [149]:
# 只将正数设置为2
np.where(arr17>0, 2, arr17)

array([[ 2.        ,  2.        ,  2.        , -0.24735368],
       [-0.64444354,  2.        ,  2.        ,  2.        ],
       [-1.18604229, -0.44967714, -0.00646522, -0.10967671],
       [-1.29897482,  2.        ,  2.        ,  2.        ]])

In [150]:
# where可以嵌套使用：
# np.where(cond1 & cond2, 0,
#                 np.where(cond1,1,
#                             np.where(cond2,2,3)))

In [151]:
# 九、排序：
# 9.1 就地排序：arr.sort()

In [154]:
arr18 = np.random.randn(5)
arr18

array([ 1.32223422,  0.3685876 , -0.37400108,  0.45767478,  0.13872729])

In [155]:
arr18.sort()

In [156]:
arr18

array([-0.37400108,  0.13872729,  0.3685876 ,  0.45767478,  1.32223422])

In [158]:
# 9.2 numpy.sort()
arr19 = np.random.randn(5)
arr19

array([ 0.58451937,  0.99699642, -1.50726486,  0.28677378, -0.12628935])

In [159]:
np.sort(arr19)

array([-1.50726486, -0.12628935,  0.28677378,  0.58451937,  0.99699642])

In [160]:
arr19

array([ 0.58451937,  0.99699642, -1.50726486,  0.28677378, -0.12628935])

In [161]:
# 1.顶级方法numpy.sort()返回的是数组的已排序的副本，不改变源数据，而就地排序会修改原数组本身
# 2.多维数组，可以传入轴编号，在该轴上进行排序

In [1]:
# numpy.linalg模块：线性代数计算
# numpy.random模块：生成多种概率分布的样本值

In [ ]:
# 注意：numpy不允许对负数使用小数幂，即便不会导致复数。
# 解决方法一：
# np.sign(a) * (np.abs(a)) ** (1 / 3)
# 解决方法二：转换类型：
# a = np.array(-1, dtype=np.complex)